[package]
name = "invaders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
crossterm = "0.26.1"
rusty_audio = "1.4.1"
rusty_time = "0.12.0"
